language: node_js
node_js:
- stable

env:
  global:
  - COMMIT_AUTHOR_EMAIL: "robot@isqua.ru"
  - SOURCE_BRANCH: "master"
  - TARGET_BRANCH: "gh-pages"

before_install:
- openssl aes-256-cbc -K $encrypted_64b2c0057057_key -iv $encrypted_64b2c0057057_iv
  -in .travis/deploy_key.enc -out .travis/deploy_key -d

deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh
  on:
    branch: master

branches:
  only:
  - master
