language: node_js
node_js:
- stable

env:
  global:
  - ENCRYPTION_LABEL: "64b2c0057057"
  - COMMIT_AUTHOR_EMAIL: "robot@isqua.ru"
  - SOURCE_BRANCH: "master"
  - TARGET_BRANCH: "gh-pages"

deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh
  on:
    branch: master

branches:
  only:
  - master
